import registerFacilityFormModel from "./registerFacilityFormModel";
const {
  formField: {
    hospitalName,
    facilityType,
    country,
    state,
    lga,
    email,
    councilRegistrationNumber,
    facilityAddress,
    website,
    ownership,
    facilityLevel,
    operationHours,
    licenceStatus,
    registrationStatus,
    premisesStatus,
    daysOfOperation,
    typesOfService,
    medicalDoctors,
    dentists,
    nurses,
    midwives,
    juniorCommunityHealthExtensionWorker,
    healthInformationManagementOfficers,
    communityHealthOfficer,
    enviromentHealthOfficer,
    pharmacyTechnicians,
    labScientists,
    phamacists,
    dentalTechnicians
  }
} = registerFacilityFormModel;

export default {
    [hospitalName.name]: '',
    [facilityType.name]: '',
    [country.name]: '',
    [state.name]: '',
    [lga.name]: '',
    [email.name]: '',
    [councilRegistrationNumber.name]: '',
    [facilityAddress.name]: '',
    [website.name]: '',
    [ownership.name]: '',
    [facilityLevel.name]: '',
    [operationHours.name]: '',
    [licenceStatus.name]: '',
    [registrationStatus.name]: '',
    [premisesStatus.name]: '',
    [daysOfOperation.name]: '',
    [typesOfService.name]: '',
    [medicalDoctors.name]: '',
    [dentists.name]: '',
    [nurses.name]: '',
    [midwives.name]: '',
    [juniorCommunityHealthExtensionWorker.name]: '',
    [healthInformationManagementOfficers.name]: '',
    [communityHealthOfficer.name]: '',
    [enviromentHealthOfficer.name]: '',
    [pharmacyTechnicians.name]: '',
    [labScientists.name]: '',
    [phamacists.name]: '',
    [dentalTechnicians.name]: ''

}
